// import { correctArgs } from './addition';
// import { add } from './addition';
// import { removeNulls } from './utils';
// import { substract } from './subtraction';

// console.log(`removeNulls, test: ${Number(add('12', '34'))} from 12 + 34`);
// console.log(`removeNulls, test: ${Number(add('2', '34'))} from 2 + 34`);
// console.log(`removeNulls, test: ${Number(add('102', '34'))} from 102 + 34`);
// console.log(`removeNulls, test: ${Number(add('89', '22'))} from 89 + 22`);

// console.log(`minus, test: ${Number(substract('132', '111'))} real: ${Number(132 - 111)}`);
// console.log('.');
// console.log('.');
// console.log('.');
// console.log('.');

// console.log(`minus, test: ${Number(substract('444', '123'))} real: ${Number(444 - 123)}`);
// console.log('.');
// console.log('.');
// console.log('.');
// console.log('.');
// console.log(`minus, test: ${Number(substract('4', '5'))} real: ${Number(4 - 5)}`);
// console.log('.');
// console.log('.');
// console.log('.');
// console.log('.');
// console.log(`minus, test: ${Number(substract('44', '51'))} real: ${Number(44 - 51)}`);
// console.log('.');
// console.log('.');
// console.log('.');
// console.log('.');
// console.log(`minus, test: ${Number(substract('444', '543'))} real: ${Number(444 - 543)}`);
// console.log('.');
// console.log('.');
// console.log('.');
// console.log('.');
// console.log(`minus, test: ${Number(substract('4404', '5403'))} real: ${Number(4404 - 5403)}`);
// console.log('.');
// console.log('.');
// console.log('.');
// console.log('.');
// console.log(`minus, test: ${Number(substract('994', '91234'))} real: ${Number(994 - 91234)}`);
// console.log('.');
// console.log('.');
// console.log('.');
// console.log('.');
// console.log(`minus, test: ${Number(substract('1000', '1'))} real: ${Number(1000 - 1)}`);
// console.log('.');
// console.log('.');
// console.log('.');
// console.log('.');


// console.log(`removeNulls, test: ${Number(removeNulls('00001000'))} from 00001000`);
// console.log(`removeNulls, test: ${Number(removeNulls('0001000'))} from 0001000`);
// console.log(`removeNulls, test: ${Number(removeNulls('001000'))} from 001000`);
// console.log(`removeNulls, test: ${Number(removeNulls('01000'))} from 01000`);
// console.log(`removeNulls, test: ${Number(removeNulls('1000'))} from 1000`);
// console.log(`removeNulls, test: ${removeNulls('00112')} from 00112`);
// console.log(`correctArgs, test: ${correctArgs('-00')} from -00`);
